import React from 'react';
import { Link } from 'react-router-dom';
import useLastVisitedPage from '../hooks/useLastVisitedPage.js';
import './css/Textblock.css';

function PrivacyPolicy() {

    useLastVisitedPage();

    return (
        <div className="textblock-container">
            <h1>PRIVACY POLICY</h1>
            <p>Last updated: 01/11/2023‍<br></br>Your privacy is important to Beacon Safe Incorporated. This privacy policy (“Privacy Policy”) applies to the Beacon Safe Incorporated websites and other services that Beacon Safe Incorporated may offer you (the “Services”) and explains how personal information is collected, used, disclosed, and protected by Beacon Safe Incorporated.</p>
            <h3>‍CHANGES TO THIS PRIVACY POLICY</h3>
            <p>We may change this Privacy Policy from time to time. If we make any material changes to this Privacy Policy, we will inform you by providing you with an in-app notification or directly by email. Otherwise, any changes to this Privacy Policy will be announced by posting the revised Privacy Policy on the Beacon Safe Incorporated website. Those changes will go into effect on the “last updated” date shown in the revised Privacy Policy. We encourage you to check this Privacy Policy whenever you use Services to understand how your personal information is used.</p>
            <h3>WHAT DOES THIS PRIVACY POLICY COVER?</h3>
            <p>In your dealings with Beacon Safe Incorporated you may provide us with personal information. Personal information for the purposes of this Privacy Policy means any information that directly or indirectly personally identifies you, like your name, street address, email address, phone number, and other personally identifiable information that you choose to give to us or that we collect in relation to your use of the Services. This Privacy Policy does not apply to the practices of entities that we do not own or control, or to individuals that we do not employ or manage.</p>
            <h3>‍NO INFORMATION FROM MINORS UNDER 13</h3>
            <p>If you are a minor less than 13 years old, please do not register for the Services or provide any personal information about yourself to us. If we learn that we have collected personal information from a minor, we will delete that information. If you are a parent of a minor, you may provide us with personal information about the minor, or permit us to collect information directly from the minor (if he or she is at least 13 years old), to use as part of the Services and we will treat it in accordance with this Privacy Policy.</p>
            <h3>‍INFORMATION COLLECTED</h3>
            <p>We collect information from you in various ways when you use the Services. Subject to applicable laws and regulations, we may also supplement this information with information from other companies. We collect two general types of information, namely personal information (defined above) and aggregate data. Our legal basis for processing such personal information will be either consent, legitimate interest, fulfillment contract or compliance with a legal obligation.Aggregate data is information we collect about a group or category of services or users from which individual user identities have been removed. In other words, no personal information is included in aggregate data. Aggregate data helps us understand trends in our users’ needs so that we can better consider new features or otherwise tailor our services. This Privacy Policy in no way restricts or limits our collection and use of aggregate data, and we may share aggregate data about our users with third parties for various purposes, including to help us better understand our customer needs and improve our services and for advertising and marketing purposes.The following are the specific types of information we collect from you:Information You Give Us. We collect information you give us through the Services and when you register for and use the Services. Examples include the following:</p>
            <h3>‍Registration and Profile Information</h3>
            <p>When you register to use the Services or update your profile, we may collect various kinds of information about you including your name, username, phone number, sms addresses, photos, email addresses and date of birth. It might also include locations, information about emergencies and incidents and contact details of your friends, family and guardians.Information we collect when you interact with Beacon Safe Incorporated.<br></br>We collect personal information of the actions taken while using or interacting with Services such as adding friends, family members and other persons you interact with, location information or information related to emergencies and incidents and communications that occur during and after such events. By agreeing to our Terms of Use you acknowledge that personal information of third parties may be obtained as a result of your use of the Service. You warrant that you shall only use the Services in accordance with our Terms of Use, and that Beacon Safe Incorporated will not be responsible for any personal information obtained in contravention of these terms.When you use the Services, we automatically collect information from your browser or mobile platform including your browser type, location, IP address, as well as the pages you visit. We may retain the details of transactions or payments you make on or related to the Services.</p>
            <h3>Location Information</h3>
            <p>Location of another user using the Services can only be done by you if such positioning services are permitted by applicable law and (i) the user is a minor and you are the parent or legal guardian of such user or a third party administrator authorized by a parent or legal guardian of such user, or (ii) the user is not a minor and the user has explicitly agreed that you may use the Services for user location purposes. To prevent abuse, Beacon Safe Incorporated will notify the user when (s)he is being located by another user. Parents or legal guardians on behalf of their children may be able to disable location services on certain Services. Beacon Safe Incorporated may log and store certain information about your use of Beacon Safe Incorporated’s Service, including but not limited to time stamps for a positioning request (search, receipt notification) and activation of the Safety Alarm (search, call, receipt notification) etc. Such information shall be logged and stored for billing and customer support purposes only, and will be retained by Beacon Safe Incorporated when you close your account in question solely for billing purposes and financial record keeping.</p>
            <h3>‍Payment Information</h3>
            <p>If you choose to use a paid Beacon Safe Incorporated account or service, our payment processing vendor collects your credit card information and billing address.</p>
            <h3>‍Submissions and Customer Service</h3>
            <p>From time to time we may request personal or demographic information and customer feedback.</p>
            <h3>‍Outside Services and Applications</h3>
            <p>Through the Services, parents or legal guardians on behalf of their children may choose to access outside services and applications, such as Facebook and other social networks. When you do, you may be able to import information from those other services and applications and share content from the Services with those outside services and applications. Some of those third party services may also provide us with information from your accounts which may enable us to enhance and personalize your use of the Services. If parents or legal guardians on behalf of their children choose to use these outside services or applications on the Services, the information you share with those outside services and applications will be covered by their privacy policies. Parents or legal guardians on behalf of their children may opt in or out of accessing outside services and applications at any time.</p>
            <h3>Automatically Collected Information</h3>
            <p>We automatically receive certain types of information when you interact with the Services and communications. For example, it is standard for your Web browser to automatically send information to every Web site you visit, including ours. That information includes your computer’s IP address, access times, your browser type and language, and referring Web site addresses. We may also collect information about the type of operating system you use, your account activity, and files and pages accessed or used by you.</p>
            <h3>‍Cookies and Web Beacons</h3>
            <p>We may also use certain kinds of technology such as cookies and Web beacons to collect information. Among other things, the use of cookies and Web beacons enables us to improve the Services and emails by seeing which areas and features are most popular, to count the number of computers, mobile phones or other devices accessing the Services, to personalize and improve your experience, to record your preferences, and to allow you to visit the Services without re entering your member ID and/or password. A cookie is a small amount of data which is sent to your browser from a Web site’s computers and stored on your computer’s hard drive. Most browsers automatically accept cookies as the default setting. You can modify your browser setting to reject our cookies or to prompt you before accepting a cookie by editing your browser options. However, if a browser is set not to accept cookies or if a user rejects a cookie, some portions of the Services may not function properly. For example, you may not be able to sign in and access certain features of the Services. A Web beacon is an electronic image, also called a “gif,” that may be used on the Services to deliver cookies, count visits and compile statistics on usage or in our emails to tell if an email has been opened and acted upon. We also use Google Analytics to help us understand how users engage with our Services. The information collected and how it is used is described at http://www.google.com/intl/en/analytics/privacyoverview.html.</p>
            <h3>USE OF PERSONAL INFORMATION</h3>
            <p>In general, we use your personal information to process your requests or transactions, to provide you with information or services you request, to inform you about other information, events, promotions, products or services related to the Services that we think will be of interest to you, to facilitate your use of and our administration and operation of the Services, and to otherwise provide the Services and serve you and our users. For example, we may use your personal information:to request feedback and to enable us to develop, customize and improve our publications, products and the Services;to conduct marketing analysis, to send you surveys or newsletters, to contact you about services, products, activities, offers from Beacon Safe Incorporated or our partners and for other marketing, informational, product development and promotional purposes related to the Services;to send you a welcoming email and to contact you about your use of the Services; to respond to your emails, submissions, comments, requests or complaints; to perform after sales services; to anticipate and resolve problems with our service; to respond to customer support inquiries, for assistance with our product and service development; and to inform you of updates to products and services from Beacon Safe Incorporated that better meet your needs; andfor other purposes about which we notify you.</p>
            <h3>‍Legal basis for using your personal information</h3>
            <p>Beacon Safe Incorporated will rely on one of the following legal grounds for processing your personal information:Contract: When you subscribe to the Services we need to process some of your personal information such as name, payment information, address and email in order to provide you with the agreed Services.Legitimate interest: We may rely on a legitimate interest when processing personal information. For example, when we collect information related to emergencies and incidents and communications that occur during and after such events, we do this for the purposes of ensuring the safety of our users.Legal obligation: We may be required to use your personal information to comply with the law.Consent: We might ask for your consent to use your information for specific purposes, for example when we wish to send you news and offers from our collaborating partners.</p>
            <h3>SHARING OF PERSONAL INFORMATION</h3>
            <p>Beacon Safe Incorporated reserves the right to share aggregated demographic information about our customers (including you), sales, and traffic to our partners and advertisers. We will not give, sell, rent, share, or trade any of your personal information or any data that you store using our services to any third party except as outlined in this Privacy Policy or with your consent. We may disclose information to a third party to (a) comply with laws or respond to lawful requests and legal process, (b) to protect Beacon Safe Incorporated, agents, customers, and others including to enforce our agreements, policies and terms of use or(c) in the good faith belief that disclosure is needed to respond to an emergency, or protect the personal safety of any person.Inviting family, friends and guardians to join: When you ask us to invite a friend, family member, or other guardian to join the the Services, we may send such person a message on your behalf using your name and contact details. The invitation may also contain information about other users such person might know. We may also send reminders to them in your name. Only invite people you know with their permission to do so. Every once in a while, we may start a business relationship with other businesses who we think are trustworthy and who have confirmed that their privacy practices are consistent with ours (“Service Providers”). For example, we may hire Service Providers to provide services like hosting and maintenance, data storage and management, and marketing and promotions. We only provide our Service Providers with the information they need to perform these services for us, and we have entered into the necessary data processing agreements with them. Each Service Provider must agree to use security procedures and practices in accordance with applicable laws and regulations, appropriate to the type of information involved, in order to protect your Personal Information from unauthorized access, use or disclosure. Service Providers are prohibited from using Personal Information except as we tell them.</p>
            <h3>NETWORK AND INFORMATION SECURITY</h3>
            <p>Beacon Safe Incorporated takes reasonable steps to protect information we collect from you to prevent loss, misuse and unauthorized access, disclosure, alteration, and destruction. The servers on which information is stored are kept in a controlled environment with limited access. The servers are for the time being located in the US, which means that if you are a United States resident your personal information will be transferred outside the United States. This transfer of data is made on the basis of an adequacy decision by the United States Commission. Your account information and access to our service is accessible only through the use of an individual user ID and password. To protect the confidentiality of personal information, you must keep your password confidential and not disclose it to any other person.<br></br>Please advise us immediately if you believe your password has been misused. In addition, always logout and close your browser when you finish your session. Please note that we will never ask you to disclose your password in an unsolicited phone call or email.Your data will be stored on our servers for as long as you are a subscriber of our Services, or until you specifically request the deletion of your personal information. When you unsubscribe from the Services we will store your data for 12 months and then delete it from our servers.‍</p>
            <h3>CHOICE/OPTOUT</h3>
            <p>Beacon Safe Incorporated may send you communications or data regarding the Services, including but not limited to (i) notices about your use of the Services, including any notices concerning violations of use, (ii) updates, and (iii) promotional information and materials regarding our products and services. You may opt out of receiving promotional emails from Beacon Safe Incorporated by following the opt out instructions provided in those emails. You may also opt out of receiving promotional emails and other promotional communications from us at any time by emailing support@beaconsafeincorporated.com with your specific request. Opt out requests will not apply to transactional service messages, such as security alerts and notices about your current account and services. Parents or legal guardians on behalf of their children may also select or disable certain features of the Services, such as Facebook login or location services, by accessing your account and changing your preferences.</p>
            <h3>CONTACTING US</h3>
            <p>Any questions about this Privacy Policy should be addressed to:<br></br>Beacon Safe Incorporated<br></br>New York, United States<br></br>support@beaconsafeincorporated.com</p>
            <h3>COMPLAINTS</h3>
            <p>‍If you’re based in New York State, you can always file a complaint with the Equal Employment Opportunity Commission or the Better Business Bureau.</p>
            <div className="return-to-login">
                <Link to={sessionStorage.getItem('lastVisitedPage') || '/'} className="return-link">← RETURN</Link>
            </div>
        </div>
    );
}

export default PrivacyPolicy;